### ISSUE TITLE
Link to API docs

### ISSUE THREAD

**Issue by muschellij2** [neuroconductor/API#2]
https://neuroconductor.org/api should link to https://neuroconductor.org/api-docs

**Comment by adigherman** [comment]
Easy fix. Can you please point to where that link resides on the website? I checked both the main menu and the home page cards and both link to https://neuroconductor.org/api-docs/overview

**Comment by adigherman** [comment]
Or do you want an Apache rewrite rule added to the system? Please be more specific.

**Comment by adigherman** [comment]
Also, https://neuroconductor.org/api-docs is currently a blank page.

**Comment by muschellij2** [comment]
api-docs should link to https://neuroconductor.org/api-docs/overview

**Comment by neuroconductor** [comment]
Done.
